import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { useMessageNotifications } from "@/hooks/useMessageNotifications";
import { isUnauthorizedError } from "@/lib/authUtils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import SchoolMasterLogo from "@/assets/schoolmaster-logo.png";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { useLocation } from "wouter";
import { Calculator, Flame, Star, Clock, BookOpen, Target, ArrowLeft, Eye, Award, Zap, Trophy, Crown, Users, Brain, ChevronDown, ChevronUp, FileText, Calendar, Video, Copy, ExternalLink, BarChart3, CheckCircle, MessageCircle, Search, Settings, Map, Mail, Package } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Link } from "wouter";
import CalendarView from "@/components/calendar/calendar-view";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { BalanceDisplay } from "@/components/payment/balance-display";
import { LessonPayment } from "@/components/payment/lesson-payment";
import { LessonActions } from "@/components/lesson/lesson-actions";
import { SubjectSidebar } from "@/components/student/subject-sidebar";
import { Navbar } from "@/components/Navbar";

export default function StudentDashboard() {
  const { toast } = useToast();
  const { isAuthenticated, isLoading, user } = useAuth();
  const [, setLocation] = useLocation();
  
  // Enable message notifications when in student dashboard
  useMessageNotifications(true);
  const [showAllBadges, setShowAllBadges] = useState(false);
  const [activeTab, setActiveTab] = useState("overview");
  const [selectedLesson, setSelectedLesson] = useState<any>(null);
  const [isLessonDialogOpen, setIsLessonDialogOpen] = useState(false);
  const [selectedStudentId, setSelectedStudentId] = useState<string | null>("student1");
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);
  const [paymentLessonId, setPaymentLessonId] = useState<string>("");
  
  // Check if this is admin demo mode (accessed from admin dashboard)
  const isDemoMode = window.location.search.includes('demo=true') || window.history.state?.fromAdmin;
  
  // Get viewAs parameter from URL for admin demo mode
  const urlParams = new URLSearchParams(window.location.search);
  const viewAsUserId = urlParams.get('viewAs');

  // Redirect to home if not authenticated (unless in demo mode)
  useEffect(() => {
    if (!isDemoMode && !isLoading && !isAuthenticated) {
      toast({
        title: "Unauthorized",
        description: "You are logged out. Logging in again...",
        variant: "destructive",
      });
      setTimeout(() => {
        window.location.href = "/api/login";
      }, 500);
      return;
    }
  }, [isAuthenticated, isLoading, toast, isDemoMode]);

  // Mock data for demo mode (only used when no real data available)
  const mockData = {
    stats: {
      currentLevel: 1,
      totalXP: 0,
      weeklyStreak: 0,
      completedLessons: 0,
      averageScore: 0, // Changed from 87 to 0 - no fake scores
    },
    upcomingLessons: [
      { 
        id: "1", 
        title: "Równania kwadratowe - podstawy", 
        scheduledAt: "2025-01-30", 
        time: "15:00", 
        tutor: "Dr Anna Kowalska",
        tutorName: "Dr Anna Kowalska",
        duration: 60,
        description: "Wprowadzenie do równań kwadratowych, wzór na deltę, znajdowanie pierwiastków",
        meetLink: null // Will be generated by Google Calendar API
      },
      { 
        id: "2", 
        title: "Funkcje liniowe", 
        scheduledAt: "2025-02-01", 
        time: "16:30", 
        tutor: "Mgr Piotr Nowak",
        tutorName: "Mgr Piotr Nowak",
        duration: 45,
        description: "Analiza funkcji liniowych, wykresy, równania prostej",
        meetLink: null // Will be generated by Google Calendar API
      },
    ],
    homeworkAssignments: [
      { id: "1", title: "Równania liniowe - ćwiczenia podstawowe", dueDate: "2025-01-30", status: "assigned", totalTasks: 10 },
      { id: "2", title: "Funkcje kwadratowe - analiza wykresów", dueDate: "2025-02-01", status: "assigned", totalTasks: 5 },
      { id: "3", title: "Geometria - właściwości trójkątów", dueDate: "2025-02-05", status: "assigned", totalTasks: 8 },
      { id: "4", title: "Ćwiczenia z algebry", dueDate: "2025-01-25", status: "graded", totalTasks: 12 },
      { id: "5", title: "Zadania z geometrii", dueDate: "2025-01-20", status: "graded", totalTasks: 6 },
      { id: "6", title: "Statystyka i prawdopodobieństwo", dueDate: "2025-01-28", status: "submitted", totalTasks: 15 },
    ],
    allBadges: [],
  };

  // Construct query for dashboard data with optional student ID for demo mode
  const queryString = isDemoMode && selectedStudentId ? `?studentId=${selectedStudentId}` : "";
  const queryKey = isDemoMode && selectedStudentId ? ["/api/student/dashboard", selectedStudentId] : ["/api/student/dashboard"];

  const { data: dashboardData, isLoading: isDashboardLoading, refetch } = useQuery({
    queryKey,
    queryFn: async () => {
      const response = await fetch(`/api/student/dashboard${queryString}`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      return response.json();
    },
    enabled: isDemoMode ? Boolean(selectedStudentId) : Boolean(isAuthenticated),
    retry: false,
    refetchOnMount: true,
    refetchOnWindowFocus: false,
    staleTime: 0, // Always fetch fresh badge data
  });

  // Get homework assignments separately
  const { data: homeworkData } = useQuery({
    queryKey: ["/api/student/homework"],
    enabled: !isDemoMode && isAuthenticated,
    retry: false,
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Get lesson invitations status
  const { data: lessonInvitations = [] } = useQuery({
    queryKey: ["/api/student/lesson-invitations"],
    enabled: !isDemoMode && isAuthenticated,
    retry: false,
    staleTime: 2 * 60 * 1000, // 2 minutes
  });

  // Get students list for demo mode selector
  const { data: studentsData } = useQuery({
    queryKey: ["/api/admin/students"],
    enabled: isDemoMode,
    retry: false,
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Get tutor matching status
  const { data: matchingStatus } = useQuery({
    queryKey: isDemoMode && selectedStudentId ? ["/api/student/matching-status", selectedStudentId] : ["/api/student/matching-status"],
    queryFn: async () => {
      const studentId = isDemoMode && selectedStudentId ? selectedStudentId : '';
      const response = await fetch(`/api/student/matching-status${studentId ? `/${studentId}` : ''}`);
      if (!response.ok) {
        if (response.status === 404) return null;
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      return response.json();
    },
    enabled: isDemoMode ? Boolean(selectedStudentId) : Boolean(isAuthenticated),
    retry: false,
    staleTime: 2 * 60 * 1000, // 2 minutes
  });

  // Get topic progression for student
  const { data: topicProgression = [] } = useQuery({
    queryKey: ["/api/student/topic-progression"],
    enabled: !isDemoMode && isAuthenticated,
    retry: false,
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Get next bookable topic (for booking new lessons)
  const { data: nextTopic } = useQuery({
    queryKey: ["/api/student/next-bookable-topic"],
    enabled: !isDemoMode && isAuthenticated,
    retry: false,
    staleTime: 2 * 60 * 1000, // 2 minutes
  });

  // Get conversations for unread message badge
  const { data: myPackages = [] } = useQuery({
    queryKey: ["/api/packages/my"],
    enabled: isAuthenticated && !isDemoMode,
  });

  const { data: conversationsData = [] } = useQuery({
    queryKey: ["/api/conversations"],
    enabled: !isDemoMode && isAuthenticated,
    retry: false,
    staleTime: 30 * 1000, // 30 seconds - refresh badge frequently
  });

  // Get loyalty program status
  const { data: loyaltyStatus, isLoading: isLoyaltyLoading } = useQuery({
    queryKey: ["/api/loyalty/status"],
    enabled: !isDemoMode && isAuthenticated,
    retry: false,
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Force refetch when selectedStudentId changes and ensure initial load
  useEffect(() => {
    if (isDemoMode && selectedStudentId) {
      refetch();
    }
  }, [selectedStudentId, refetch, isDemoMode]);

  // Set selectedStudentId from viewAs parameter or default when students data is loaded in demo mode
  useEffect(() => {
    if (isDemoMode && studentsData && Array.isArray(studentsData) && studentsData.length > 0) {
      // If viewAs parameter exists, use that student ID
      if (viewAsUserId) {
        const targetStudent = studentsData.find((student: any) => student.id === viewAsUserId);
        if (targetStudent) {
          setSelectedStudentId(viewAsUserId);
          return;
        }
      }
      
      // Otherwise, use default logic if no selectedStudentId
      if (!selectedStudentId) {
        setSelectedStudentId(studentsData[0].id);
      }
    }
  }, [isDemoMode, studentsData, selectedStudentId, viewAsUserId]);

  const handleLogout = async () => {
    if (isDemoMode) {
      setLocation("/admin-dashboard");
    } else {
      try {
        await fetch("/api/auth/logout", { method: "POST" });
        window.location.href = "/login";
      } catch (error) {
        console.error("Logout error:", error);
        window.location.href = "/login";
      }
    }
  };

  const handleViewLessonDetails = (lesson: any) => {
    setSelectedLesson(lesson);
    setIsLessonDialogOpen(true);
  };

  const handleJoinLesson = (lesson: any) => {
    // Check if lesson is paid
    const isPaid = lesson.paymentStatus === 'paid' || lesson.isPaid;
    if (!isPaid) {
      toast({
        title: "Lekcja nieopłacona",
        description: "Musisz opłacić lekcję przed dołączeniem. Kliknij przycisk 'Opłać'.",
        variant: "destructive",
      });
      return;
    }

    if (lesson.meetLink) {
      window.open(lesson.meetLink, '_blank');
      toast({
        title: "Przekierowanie do Google Meet",
        description: "Otwieranie spotkania w nowej karcie...",
      });
    } else {
      toast({
        title: "Brak linku do spotkania",
        description: "Link Google Meet nie został jeszcze wygenerowany.",
        variant: "destructive",
      });
    }
  }

  const handleCopyMeetLink = async (lesson: any) => {
    if (lesson.meetLink) {
      try {
        await navigator.clipboard.writeText(lesson.meetLink);
        toast({
          title: "Link skopiowany",
          description: "Link Google Meet został skopiowany do schowka.",
        });
      } catch (error) {
        toast({
          title: "Błąd kopiowania",
          description: "Nie udało się skopiować linku.",
          variant: "destructive",
        });
      }
    }
  };

  const handleCancelLesson = async (lesson: any) => {
    if (isDemoMode) {
      toast({
        title: "Tryb demo",
        description: "Anulowanie lekcji nie jest dostępne w trybie demo.",
        variant: "destructive",
      });
      return;
    }

    try {
      const response = await fetch(`/api/lessons/${lesson.id}/cancel`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          reason: 'Anulowanie przez ucznia',
        }),
      });

      if (response.ok) {
        toast({
          title: "Lekcja anulowana",
          description: "Lekcja została pomyślnie anulowana.",
        });
        // Refresh the data
        refetch();
      } else {
        throw new Error('Błąd anulowania lekcji');
      }
    } catch (error) {
      toast({
        title: "Błąd",
        description: "Nie udało się anulować lekcji. Spróbuj ponownie.",
        variant: "destructive",
      });
    }
  };

  // Show loading only if not in demo mode and actually loading
  if (!isDemoMode && isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-navy-900"></div>
      </div>
    );
  }
  
  // Show loading for dashboard data (both demo mode and regular mode)
  if (isDashboardLoading && (isDemoMode ? selectedStudentId : true)) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-navy-900"></div>
      </div>
    );
  }

  // Use real data from API - never fallback to mock data for logged-in users
  const data = isDemoMode ? 
    (selectedStudentId && dashboardData ? dashboardData : mockData) :
    dashboardData || { stats: { totalXP: 0, currentLevel: 1, weeklyStreak: 0, completedLessons: 0, averageScore: 0 }, upcomingLessons: [] };
  
  const stats = data?.stats || { totalXP: 0, currentLevel: 1, weeklyStreak: 0, completedLessons: 0, averageScore: 0 };
  const upcomingLessons = data?.upcomingLessons || [];
  
  // Get nearest upcoming lesson
  const nearestLesson = upcomingLessons.length > 0 ? upcomingLessons[0] : null;
  // Use real homework data when available, never show mock data for logged users
  const allHomeworkAssignments = (!isDemoMode && homeworkData) ? homeworkData : 
                                (isDemoMode && data?.homeworkAssignments) ? data.homeworkAssignments : 
                                [];
  
  // Map badges with proper icon mapping
  const iconMap: any = {
    Calculator, Target, BookOpen, Flame, Star, Brain, Zap, Users, Crown, Trophy, Award
  };

  const allBadges = (data?.badges && data.badges.length > 0) ? 
    data.badges.map((badge: any) => ({
      ...badge,
      icon: iconMap[badge.icon] || BookOpen,
      color: badge.unlocked 
        ? badge.category === 'algebra' ? 'bg-accent text-navy-900'
        : badge.category === 'geometry' ? 'bg-navy-600 text-white'
        : badge.category === 'functions' ? 'bg-green-600 text-white'
        : badge.category === 'streak' ? 'bg-orange-500 text-white'
        : badge.category === 'homework' ? 'bg-purple-600 text-white'
        : badge.category === 'difficulty' ? 'bg-blue-600 text-white'
        : 'bg-emerald-600 text-white'
        : 'bg-gray-200 text-gray-400'
    })) : 
    (data?.allBadges && data.allBadges.length > 0) ? data.allBadges : 
    mockData.allBadges;
  
  // Sort homework: assigned first (niezrobione), then submitted, then graded
  const homeworkAssignments = [...allHomeworkAssignments].sort((a: any, b: any) => {
    const statusOrder: { [key: string]: number } = { 'assigned': 0, 'submitted': 1, 'graded': 2 };
    return statusOrder[a.status] - statusOrder[b.status];
  });



  return (
    <>
      <Navbar />
      <div className="h-screen bg-gray-50 flex">
        {/* Subject Sidebar */}
        <SubjectSidebar />
        
        {/* Main Content Area */}
        <div className="flex-1 flex flex-col min-w-0 h-screen">
          {/* Main Dashboard Content */}
        <div className="flex-1 overflow-y-auto">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-4 sm:py-6 lg:py-8 min-w-0">
        
        {/* Demo Mode Selector */}
        {isDemoMode && (
          <div className="mb-6 flex items-center justify-between p-4 bg-orange-50 border border-orange-200 rounded-lg">
            <div className="flex items-center gap-2">
              <span className="text-sm bg-orange-100 text-orange-800 px-2 py-1 rounded-full flex items-center gap-1">
                <Eye className="w-3 h-3" />
                Podgląd ucznia
              </span>
              <Select value={selectedStudentId || "student1"} onValueChange={setSelectedStudentId}>
                <SelectTrigger className="w-64">
                  <SelectValue placeholder="Wybierz ucznia" />
                </SelectTrigger>
                <SelectContent>
                  {(studentsData as any)?.filter((student: any, index: number, self: any[]) => 
                    self.findIndex(s => s.id === student.id) === index
                  ).map((student: any) => (
                    <SelectItem key={student.id} value={student.id}>
                      {student.firstName} {student.lastName} ({student.email})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <Button 
              onClick={() => setLocation("/admin-dashboard")} 
              variant="outline"
              size="sm"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Powrót do panelu
            </Button>
          </div>
        )}

        {/* Welcome Section */}
        <div className="flex flex-col xl:flex-row justify-between items-start xl:items-center mb-6 lg:mb-8 gap-3 lg:gap-4 min-w-0">
          <div className="min-w-0 flex-1">
            <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold text-navy-900">
              Cześć, {(() => {
                if (isDemoMode && selectedStudentId) {
                  const selectedStudent = (studentsData as any)?.find((s: any) => s.id === selectedStudentId);
                  return selectedStudent?.firstName || "Uczniu";
                } else {
                  return (user as any)?.firstName || "Uczniu";
                }
              })()}! 👋
            </h1>
            <p className="text-sm sm:text-base text-gray-600">Gotowy na kolejną lekcję matematyki?</p>
          </div>
          {/* Show streak and XP always */}
          {(
            <div className="flex items-center space-x-2 sm:space-x-3 flex-shrink-0">
              <div className="bg-accent rounded-full px-2 sm:px-3 py-1 sm:py-2 flex items-center space-x-1 sm:space-x-2">
                <Flame className="text-navy-900 w-3 h-3 sm:w-4 sm:h-4" />
                <span className="font-bold text-navy-900 text-xs sm:text-sm">{stats.weeklyStreak || stats.streak || 0} dni</span>
              </div>
              <div className="bg-navy-900 rounded-full px-2 sm:px-3 py-1 sm:py-2 flex items-center space-x-1 sm:space-x-2">
                <Star className="text-accent w-3 h-3 sm:w-4 sm:h-4" />
                <span className="font-bold text-white text-xs sm:text-sm">{stats.totalXP || stats.xp || 0} XP</span>
              </div>
            </div>
          )}
        </div>

        {/* Progress Overview - pokazuj zawsze */}
        {(
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 lg:gap-8 mb-6 lg:mb-8 min-w-0">
          <div className="lg:col-span-2 min-w-0">
            <Card>
              <CardHeader>
                <CardTitle className="text-xl sm:text-2xl font-bold text-navy-900">
                  Twój postęp
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-gray-50 rounded-xl p-4 sm:p-6 lg:p-8">
                  <div className="flex justify-between items-center mb-4">
                    <span className="font-semibold text-navy-900 text-sm sm:text-base truncate">
                      Poziom {nextTopic?.topicOrder ? (
                        nextTopic.topicOrder <= 7 ? 1 :
                        nextTopic.topicOrder <= 13 ? 2 :
                        nextTopic.topicOrder <= 18 ? 3 :
                        nextTopic.topicOrder <= 22 ? 4 :
                        nextTopic.topicOrder <= 26 ? 5 :
                        nextTopic.topicOrder <= 29 ? 6 : 7
                      ) : 1} - Matematyka klasy 8
                    </span>
                    <span className="text-navy-600 font-bold text-sm sm:text-base">
                      {(() => {
                        if (!nextTopic) return "0%";
                        const currentChapter = nextTopic.topicOrder <= 7 ? 1 : nextTopic.topicOrder <= 13 ? 2 : nextTopic.topicOrder <= 18 ? 3 : nextTopic.topicOrder <= 22 ? 4 : nextTopic.topicOrder <= 26 ? 5 : nextTopic.topicOrder <= 29 ? 6 : 7;
                        const chapterSizes = [7, 6, 5, 4, 4, 3, 3];
                        const chapterTotal = chapterSizes[currentChapter - 1];
                        const completed = stats.totalLessons > 0 ? 1 : 0;
                        return `${Math.round((completed / chapterTotal) * 100)}%`;
                      })()}
                    </span>
                  </div>
                  <div className="relative h-4 w-full overflow-hidden rounded-full bg-navy-200 border-2 border-navy-300 mb-4">
                    <div 
                      className="h-full bg-gradient-to-r from-accent via-yellow-400 to-yellow-500 rounded-full transition-all duration-500 ease-out shadow-inner"
                      style={{ width: `${(() => {
                        if (!nextTopic) return 0;
                        const currentChapter = nextTopic.topicOrder <= 7 ? 1 : nextTopic.topicOrder <= 13 ? 2 : nextTopic.topicOrder <= 18 ? 3 : nextTopic.topicOrder <= 22 ? 4 : nextTopic.topicOrder <= 26 ? 5 : nextTopic.topicOrder <= 29 ? 6 : 7;
                        const chapterSizes = [7, 6, 5, 4, 4, 3, 3];
                        const chapterTotal = chapterSizes[currentChapter - 1];
                        const completed = stats.totalLessons > 0 ? 1 : 0;
                        return Math.round((completed / chapterTotal) * 100);
                      })()}%` }}
                    ></div>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4 text-xs sm:text-sm">
                    <div className="flex justify-between">
                      <span className="text-gray-600">Ukończone lekcje w tym dziale:</span>
                      <span className="font-semibold text-navy-900">
                        {(() => {
                          if (!nextTopic) return "0/0";
                          const currentChapter = nextTopic.topicOrder <= 7 ? 1 : nextTopic.topicOrder <= 13 ? 2 : nextTopic.topicOrder <= 18 ? 3 : nextTopic.topicOrder <= 22 ? 4 : nextTopic.topicOrder <= 26 ? 5 : nextTopic.topicOrder <= 29 ? 6 : 7;
                          const chapterSizes = [7, 6, 5, 4, 4, 3, 3]; // lessons per chapter
                          const chapterTotal = chapterSizes[currentChapter - 1];
                          const completed = stats.totalLessons > 0 ? 1 : 0;
                          return `${completed}/${chapterTotal}`;
                        })()}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Średnia ocena:</span>
                      <span className="font-semibold text-navy-900">{stats.averageScore ? stats.averageScore.toFixed(1) : '0'}/5</span>
                    </div>
                  </div>
                  
                  {/* Nearest Lesson Section - Show nearest scheduled lesson */}
                  {nearestLesson ? (
                    <div className="mt-3 sm:mt-4 pt-3 sm:pt-4 border-t border-gray-200">
                      <div className="mb-3">
                        <h4 className="font-semibold text-navy-900 text-sm flex items-center gap-2">
                          <Calendar className="w-4 h-4 text-accent" />
                          Twoja najbliższa lekcja
                        </h4>
                      </div>
                      <div className="bg-green-50 border border-green-200 rounded-lg p-4 hover:bg-green-100 transition-colors">
                        <div className="flex items-center justify-between mb-3">
                          <div className="flex items-center gap-3">
                            <Calendar className="w-5 h-5 text-green-600" />
                            <div>
                              <h5 className="font-semibold text-navy-900 text-sm">
                                {nearestLesson.topicId ? `${nearestLesson.topicId} - ${nearestLesson.topicName || nearestLesson.title}` : nearestLesson.title}
                              </h5>
                              <p className="text-xs text-gray-600">
                                {new Date(nearestLesson.scheduledAt).toLocaleDateString('pl-PL', { 
                                  weekday: 'long', 
                                  year: 'numeric', 
                                  month: 'long', 
                                  day: 'numeric' 
                                })} o {new Date(nearestLesson.scheduledAt).toLocaleTimeString('pl-PL', { 
                                  hour: '2-digit', 
                                  minute: '2-digit' 
                                })}
                              </p>
                            </div>
                          </div>
                        </div>
                        <p className="text-xs text-gray-600 mb-3">
                          Korepetytor: {nearestLesson.tutorName}
                          {nearestLesson.topicDescription && ` • ${nearestLesson.topicDescription}`}
                        </p>
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Button 
                              size="sm"
                              variant="outline"
                              className="text-xs"
                              onClick={() => nearestLesson.topicId && setLocation(`/topic-materials/${nearestLesson.topicId}`)}
                              disabled={!nearestLesson.topicId}
                            >
                              <FileText className="w-3 h-3 mr-1" />
                              Materiały
                            </Button>
                            {/* Always show Join button - generate meeting URL if needed */}
                            <Button 
                              size="sm"
                              className="bg-green-600 hover:bg-green-700 text-white text-xs"
                              onClick={() => {
                                if (nearestLesson.meetingUrl) {
                                  window.open(nearestLesson.meetingUrl, '_blank');
                                } else {
                                  // For lessons without meeting URL, redirect to lesson details or generate one
                                  setLocation(`/lesson/${nearestLesson.id}`);
                                }
                              }}
                            >
                              <Video className="w-3 h-3 mr-1" />
                              Dołącz do lekcji
                            </Button>
                          </div>
                        </div>
                      </div>
                    </div>
                  ) : null}

                  {/* Next Topic Section - Show next available topic for booking */}
                  {nextTopic && (
                    <div className="mt-3 sm:mt-4 pt-3 sm:pt-4 border-t border-gray-200">
                      <div className="mb-3">
                        <h4 className="font-semibold text-navy-900 text-sm flex items-center gap-2">
                          <Target className="w-4 h-4 text-accent" />
                          Zarezerwuj kolejną lekcję
                        </h4>
                      </div>
                      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 hover:bg-blue-100 transition-colors">
                        <div className="flex items-center justify-between mb-3">
                          <div className="flex items-center gap-3">
                            <Target className="w-5 h-5 text-accent" />
                            <div>
                              <h5 className="font-semibold text-navy-900 text-sm">{nextTopic.name || nextTopic.topicName}</h5>
                              <p className="text-xs text-gray-600">
                                {nextTopic.id || nextTopic.topicId} • 
                                Dział {(() => {
                                  const order = nextTopic.order || nextTopic.topicOrder;
                                  return order <= 7 ? 1 : order <= 13 ? 2 : order <= 18 ? 3 : order <= 22 ? 4 : order <= 26 ? 5 : order <= 29 ? 6 : 7;
                                })()} • 
                                Lekcja #{nextTopic.order || nextTopic.topicOrder}
                              </p>
                            </div>
                          </div>
                        </div>
                        <p className="text-xs text-gray-600 mb-3">{nextTopic.topicDescription}</p>
                        <div className="flex items-center justify-between mb-2">
                          <div className="flex items-center gap-4 text-xs text-gray-600">
                            <div className="flex items-center gap-1">
                              <Clock className="w-3 h-3" />
                              <span>{nextTopic.estimatedDuration || 60} min</span>
                            </div>
                            <div className="flex items-center gap-1">
                              <Zap className="w-3 h-3 text-accent" />
                              <span>+{nextTopic.xpReward || 50} XP</span>
                            </div>
                          </div>
                          <Button 
                            size="sm"
                            className="bg-accent text-navy-900 hover:bg-accent/90 text-xs"
                            onClick={() => setLocation("/find-tutor?topic=" + nextTopic.topicId)}
                          >
                            <Users className="w-3 h-3 mr-1" />
                            Zarezerwuj
                          </Button>
                        </div>
                        <div className="text-xs text-blue-600 bg-blue-100 rounded px-2 py-1">
                          💡 Możesz rezerwować kolejne lekcje na zapas już teraz!
                        </div>
                      </div>
                    </div>
                  )}
                  
                  <div className="mt-3 sm:mt-4 pt-3 sm:pt-4 border-t border-gray-200">
                    <div className="text-center">
                      <Button 
                        variant="ghost" 
                        size="sm" 
                        onClick={() => setLocation("/student-progress")}
                        className="text-navy-600 hover:text-navy-800 text-xs sm:text-sm"
                      >
                        Zobacz wszystkie
                      </Button>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          <div className="space-y-4 lg:space-y-6 min-w-0">
            {/* Balance Display Component */}
            {!isDemoMode && <BalanceDisplay />}
            
            {/* Loyalty Program Card */}
            {!isDemoMode && loyaltyStatus && loyaltyStatus.level > 1 && (
              <Card className="border-yellow-200 bg-gradient-to-br from-yellow-50 to-amber-50">
                <CardHeader>
                  <CardTitle className="text-lg font-bold text-navy-900 flex items-center gap-2">
                    <Crown className="w-5 h-5 text-yellow-600" />
                    Program Lojalnościowy
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {/* Level and Progress */}
                  <div className="bg-white rounded-lg p-4 border border-yellow-200">
                    <div className="flex items-center justify-between mb-3">
                      <div>
                        <p className="text-xs text-gray-600">Twój poziom</p>
                        <p className="text-xl font-bold text-navy-900" data-testid="text-loyalty-level">
                          Level {loyaltyStatus.level} - {loyaltyStatus.levelName}
                        </p>
                      </div>
                      <Trophy className="w-8 h-8 text-yellow-600" />
                    </div>
                    
                    {loyaltyStatus.nextLevelAt && (
                      <div className="space-y-2">
                        <div className="flex justify-between text-xs text-gray-600">
                          <span>Postęp do następnego poziomu</span>
                          <span className="font-semibold" data-testid="text-loyalty-progress">
                            {loyaltyStatus.completedLessons} / {loyaltyStatus.nextLevelAt}
                          </span>
                        </div>
                        <div className="relative h-3 w-full overflow-hidden rounded-full bg-gray-200">
                          <div 
                            className="h-full bg-gradient-to-r from-yellow-400 to-amber-500 rounded-full transition-all duration-500"
                            style={{ width: `${Math.min((loyaltyStatus.completedLessons / loyaltyStatus.nextLevelAt) * 100, 100)}%` }}
                          ></div>
                        </div>
                        <p className="text-xs text-center text-gray-600">
                          {loyaltyStatus.lessonsToNextLevel} {loyaltyStatus.lessonsToNextLevel === 1 ? 'lekcja' : loyaltyStatus.lessonsToNextLevel < 5 ? 'lekcje' : 'lekcji'} do następnego poziomu
                        </p>
                      </div>
                    )}
                  </div>

                  {/* Benefits */}
                  <div className="grid grid-cols-2 gap-3">
                    <div className="bg-white rounded-lg p-3 border border-yellow-200 text-center">
                      <p className="text-2xl font-bold text-yellow-600" data-testid="text-loyalty-discount">
                        {loyaltyStatus.discount}%
                      </p>
                      <p className="text-xs text-gray-600">Rabat na lekcje</p>
                    </div>
                    <div className="bg-white rounded-lg p-3 border border-yellow-200 text-center">
                      <p className="text-2xl font-bold text-green-600" data-testid="text-loyalty-balance">
                        {parseFloat(loyaltyStatus.balance || '0').toFixed(2)} zł
                      </p>
                      <p className="text-xs text-gray-600">Bonusy</p>
                    </div>
                  </div>

                  <p className="text-xs text-gray-600 text-center px-2" data-testid="text-loyalty-description">
                    {loyaltyStatus.description}
                  </p>
                </CardContent>
              </Card>
            )}
            
            {/* Packages Display */}
            {!isDemoMode && (myPackages as any[]).filter((pkg: any) => pkg.status === 'active' && pkg.lessonsRemaining > 0).length > 0 && (
              <Card className="border-green-200 bg-gradient-to-br from-green-50 to-emerald-50">
                <CardHeader>
                  <div className="flex justify-between items-center">
                    <CardTitle className="text-lg font-bold text-navy-900 flex items-center gap-2">
                      <Package className="w-5 h-5 text-green-600" />
                      Twoje pakiety
                    </CardTitle>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setLocation("/student-packages")}
                      className="text-green-700 border-green-300 hover:bg-green-100"
                      data-testid="button-view-packages"
                    >
                      Zobacz wszystkie
                    </Button>
                  </div>
                </CardHeader>
                <CardContent className="space-y-3">
                  {(myPackages as any[])
                    .filter((pkg: any) => pkg.status === 'active' && pkg.lessonsRemaining > 0)
                    .slice(0, 2)
                    .map((pkg: any) => (
                      <div key={pkg.id} className="flex items-center justify-between p-3 bg-white rounded-lg border border-green-200">
                        <div className="flex-1">
                          <p className="text-sm font-semibold text-navy-900">{pkg.package?.name || 'Pakiet lekcji'}</p>
                          <p className="text-xs text-gray-600">
                            {pkg.lessonsUsed} z {pkg.lessonsTotal} wykorzystane
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="text-2xl font-bold text-green-600">{pkg.lessonsRemaining}</p>
                          <p className="text-xs text-gray-600">pozostało</p>
                        </div>
                      </div>
                    ))}
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setLocation("/student-packages")}
                    className="w-full text-green-700 hover:bg-green-100"
                    data-testid="button-buy-package"
                  >
                    <Package className="w-4 h-4 mr-2" />
                    Kup więcej pakietów
                  </Button>
                </CardContent>
              </Card>
            )}
            
            <Card>
              <CardHeader>
                <div className="flex justify-between items-center">
                  <CardTitle className="text-xl sm:text-2xl font-bold text-navy-900">Odznaki</CardTitle>
                  <Badge variant="outline" className="text-navy-600 text-xs">
                    {allBadges.filter((badge: any) => badge.unlocked).length} / {allBadges.length}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-3 gap-2 mb-4">
                  {allBadges.slice(0, showAllBadges ? undefined : 6).map((badge: any, index: number) => {
                    const IconComponent = badge.icon;
                    return (
                      <div 
                        key={index} 
                        className={`${badge.color} rounded-lg p-2 flex flex-col items-center justify-center min-h-[60px] text-center transition-all duration-200 hover:scale-105 ${
                          badge.unlocked ? 'shadow-md' : 'opacity-50'
                        }`}
                      >
                        <IconComponent className="w-5 h-5 mb-1" />
                        <div className="text-xs font-semibold break-words leading-tight">{badge.name}</div>
                      </div>
                    );
                  })}
                </div>
                
                {allBadges.length > 6 && (
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setShowAllBadges(!showAllBadges)}
                    className="w-full text-navy-600 border-navy-200 hover:bg-navy-50"
                  >
                    {showAllBadges ? (
                      <>
                        <ChevronUp className="w-4 h-4 mr-2" />
                        Pokaż mniej
                      </>
                    ) : (
                      <>
                        <ChevronDown className="w-4 h-4 mr-2" />
                        Pokaż więcej ({allBadges.length - 6} więcej)
                      </>
                    )}
                  </Button>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
        )}



        {/* Upcoming Lessons & Tasks */}
        <div className="grid lg:grid-cols-2 gap-4 sm:gap-6 lg:gap-8">
          <Card>
            <CardHeader>
              <CardTitle className="text-xl sm:text-2xl font-bold text-navy-900">Nadchodzące lekcje</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4 max-h-96 overflow-y-auto">
                {(() => {
                  // Get real upcoming lessons
                  const realUpcomingLessons = isDemoMode ? mockData.upcomingLessons : (dashboardData?.upcomingLessons || []);
                  
                  // Convert pending invitations to lesson-like format for display
                  const pendingInvitations = !isDemoMode ? (lessonInvitations || [])
                    .filter((invitation: any) => invitation.status === 'pending')
                    .map((invitation: any) => ({
                      id: `invitation-${invitation.id}`,
                      title: `Zaproszenie: ${invitation.subjectName}`,
                      description: `Oczekuje na odpowiedź od ${invitation.tutorName}`,
                      scheduledAt: invitation.sentAt, // Use sentAt as placeholder date
                      duration: 60,
                      status: "invitation-pending",
                      paymentStatus: "unpaid", 
                      price: "100.00",
                      tutorName: invitation.tutorName,
                      isInvitation: true,
                      invitationId: invitation.id,
                      invitationData: invitation
                    })) : [];

                  // Combine and sort all upcoming lessons
                  const allUpcomingLessons = [...realUpcomingLessons, ...pendingInvitations]
                    .sort((a, b) => new Date(a.scheduledAt).getTime() - new Date(b.scheduledAt).getTime());

                  return allUpcomingLessons.length > 0 
                    ? allUpcomingLessons.map((lesson: any, index: number) => {
                    const isPastLesson = new Date(lesson.scheduledAt) < new Date();
                    const isPaid = lesson.paymentStatus === 'paid' || lesson.isPaid;
                    
                    return (
                      <div key={index} className={`${
                        isPastLesson 
                          ? 'bg-gray-50 border border-gray-200 opacity-60' 
                          : 'bg-white border border-gray-200'
                      } rounded-lg p-3 hover:shadow-sm transition-shadow`}>
                        <div className="flex items-center justify-between mb-2">
                          <div className="flex-1">
                            <h3 className={`font-medium text-sm ${
                              isPastLesson ? 'text-gray-600' : 'text-navy-900'
                            }`}>{lesson.title}</h3>
                            <p className={`text-xs ${
                              isPastLesson ? 'text-gray-500' : 'text-gray-600'
                            }`}>
                              {new Date(lesson.scheduledAt).toLocaleDateString("pl-PL")} • {new Date(lesson.scheduledAt).toLocaleTimeString("pl-PL", { hour: '2-digit', minute: '2-digit' })}
                            </p>
                          </div>
                          <div className="flex items-center gap-2">
                            {/* Status badge */}
                            {lesson.status === "invitation-pending" && (
                              <Badge variant="secondary" className="text-xs px-2 py-0.5 bg-yellow-100 text-yellow-800 border-yellow-200">
                                Oczekuje na korepetytora
                              </Badge>
                            )}
                            
                            {lesson.status === "pending" && (
                              <Badge variant="secondary" className="text-xs px-2 py-0.5 bg-yellow-100 text-yellow-800 border-yellow-200">
                                Oczekuje potwierdzenia
                              </Badge>
                            )}
                            
                            {!isPastLesson && lesson.status !== "pending" && lesson.status !== "invitation-pending" && (
                              <Badge variant={isPaid ? "default" : "secondary"} className={`text-xs px-2 py-0.5 ${
                                isPaid ? 'bg-green-100 text-green-800 border-green-200' : 'bg-orange-100 text-orange-800 border-orange-200'
                              }`}>
                                {isPaid ? 'Opłacona' : 'Nieopłacona'}
                              </Badge>
                            )}
                            
                            <Badge variant="outline" className={`text-xs px-2 py-0.5 ${
                              isPastLesson 
                                ? 'bg-gray-100 text-gray-500 border-gray-300' 
                                : lesson.status === "pending" || lesson.status === "invitation-pending"
                                  ? 'bg-yellow-50 text-yellow-700 border-yellow-200'
                                  : 'bg-blue-50 text-blue-700 border-blue-200'
                            }`}>
                            {isPastLesson ? 'Zakończona' : 
                             lesson.status === "pending" ? 'Oczekuje' : 
                             lesson.status === "invitation-pending" ? 'Wysłane' : (() => {
                              const today = new Date();
                              const lessonDate = new Date(lesson.scheduledAt);
                              const timeDiff = lessonDate.getTime() - today.getTime();
                              const daysDiff = Math.ceil(timeDiff / (1000 * 3600 * 24));
                              
                              if (daysDiff === 0) return 'Dziś';
                              if (daysDiff === 1) return 'Jutro';
                              if (daysDiff < 0) return 'Zakończona';
                              return `Za ${daysDiff} dni`;
                            })()}
                            </Badge>
                          </div>
                        </div>
                        
                        {/* Show recording link for completed lessons */}
                        {isPastLesson && lesson.status === 'completed' && lesson.recordingUrl && (
                          <div className="mb-2 p-2 bg-purple-50 rounded-lg">
                            <div className="flex items-center justify-between gap-2">
                              <div className="flex items-center gap-2">
                                <Video className="w-4 h-4 text-purple-600 flex-shrink-0" />
                                <span className="text-xs font-medium text-purple-900">Nagranie dostępne</span>
                              </div>
                              <a
                                href={lesson.recordingUrl}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-xs text-purple-600 hover:text-purple-800 flex items-center gap-1 font-medium"
                                data-testid={`link-student-recording-${lesson.id}`}
                              >
                                Obejrzyj nagranie
                                <ExternalLink className="w-3 h-3" />
                              </a>
                            </div>
                          </div>
                        )}
                        
                        <div className="flex gap-2">
                          {!isPastLesson && !isPaid && !isDemoMode ? (
                            <>
                              <Button 
                                size="sm"
                                className="flex-1 bg-blue-600 text-white hover:bg-blue-700"
                                onClick={() => {
                                  setPaymentLessonId(lesson.id);
                                  setIsPaymentModalOpen(true);
                                }}
                              >
                                Opłać lekcję
                              </Button>
                              <Button 
                                size="sm"
                                variant="outline"
                                className="border-red-300 text-red-600 hover:bg-red-50"
                                onClick={() => handleCancelLesson(lesson)}
                              >
                                Anuluj
                              </Button>
                            </>
                          ) : isPastLesson ? (
                            <Button 
                              size="sm"
                              className="flex-1 bg-gray-400 text-gray-600 cursor-not-allowed"
                              disabled
                              data-testid={`button-lesson-completed-${lesson.id}`}
                            >
                              Zakończona
                            </Button>
                          ) : !isPaid ? (
                            <>
                              <Button 
                                size="sm"
                                className="flex-1 bg-blue-600 text-white hover:bg-blue-700"
                                onClick={() => {
                                  setPaymentLessonId(lesson.id);
                                  setIsPaymentModalOpen(true);
                                }}
                              >
                                Opłać lekcję
                              </Button>
                              <Button 
                                size="sm"
                                variant="outline"
                                className="border-red-300 text-red-600 hover:bg-red-50"
                                onClick={() => handleCancelLesson(lesson)}
                              >
                                Anuluj
                              </Button>
                            </>
                          ) : (
                            <>
                              <Button 
                                size="sm"
                                className="flex-1 bg-green-600 text-white hover:bg-green-700"
                                onClick={() => handleJoinLesson(lesson)}
                              >
                                Dołącz
                              </Button>
                              <Button 
                                size="sm"
                                variant="outline"
                                className="border-red-300 text-red-600 hover:bg-red-50"
                                onClick={() => handleCancelLesson(lesson)}
                              >
                                Anuluj
                              </Button>
                            </>
                          )}
                        </div>
                      </div>
                    );
                    })
                    : (
                      <div className="text-center py-12 text-gray-500">
                        <Clock className="w-12 h-12 mx-auto mb-3 text-gray-400" />
                        <p className="text-lg font-medium mb-2">Brak zaplanowanych lekcji</p>
                        <p className="text-sm">Umów się na nową lekcję z korepetytorem</p>
                      </div>
                    );
                })()}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle className="text-xl sm:text-2xl font-bold text-navy-900">Zadania domowe</CardTitle>
              <Link href="/student-homework">
                <Button variant="outline" size="sm" className="text-navy-600 border-navy-200 hover:bg-navy-50">
                  <FileText className="w-4 h-4 mr-2" />
                  Pokaż wszystkie
                </Button>
              </Link>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {homeworkAssignments.length > 0 ? (
                  homeworkAssignments.slice(0, 3).map((assignment: any, index: number) => (
                    <div key={`homework-${index}`} className="block">
                      <Link href="/student-homework">
                        <div className={`${
                          assignment.status === 'assigned' ? 'bg-accent/10 border border-accent' : 
                          assignment.status === 'submitted' ? 'bg-blue-50 border border-blue-200' :
                          'bg-green-50 border border-green-200'
                        } rounded-lg p-4 cursor-pointer hover:shadow-md transition-all duration-200 block`}>
                          <div className="flex items-start justify-between mb-2">
                            <h3 className="font-semibold text-navy-900 text-sm leading-tight">{assignment.title}</h3>
                            <Badge 
                              variant={
                                assignment.status === 'assigned' ? 'default' : 
                                assignment.status === 'submitted' ? 'outline' : 
                                'secondary'
                              }
                              className="ml-2 text-xs flex-shrink-0"
                            >
                              {assignment.status === 'assigned' ? 'Do zrobienia' : 
                               assignment.status === 'submitted' ? 'Wysłane' : 
                               'Ocenione'}
                            </Badge>
                          </div>
                          <p className="text-xs text-gray-600 mb-2">
                            {assignment.totalTasks} {assignment.totalTasks === 1 ? 'zadanie' : assignment.totalTasks < 5 ? 'zadania' : 'zadań'} • Termin: {new Date(assignment.dueDate).toLocaleDateString("pl-PL")}
                          </p>
                          {assignment.status === 'assigned' ? (
                            <div className="flex items-center gap-2 text-xs text-accent font-medium">
                              <Clock className="w-3 h-3" />
                              Do zrobienia
                            </div>
                          ) : assignment.status === 'submitted' ? (
                            <div className="flex items-center gap-2 text-xs text-blue-600 font-medium">
                              <FileText className="w-3 h-3" />
                              Oczekuje na ocenę
                            </div>
                          ) : (
                            <div className="flex items-center gap-2 text-xs text-green-600 font-medium">
                              <CheckCircle className="w-3 h-3" />
                              Ocenione
                            </div>
                          )}
                        </div>
                      </Link>
                    </div>
                  ))
                ) : (
                  <div className="text-center py-8 text-gray-500">
                    <FileText className="w-8 h-8 mx-auto mb-2 text-gray-400" />
                    <p className="text-sm">Brak zadań domowych</p>
                  </div>
                )}
                
                {homeworkAssignments.length > 3 && (
                  <div className="pt-2 border-t border-gray-100">
                    <Link href="/student-homework">
                      <Button variant="outline" className="w-full text-navy-600 border-navy-200 hover:bg-navy-50 text-xs">
                        <FileText className="w-3 h-3 mr-2" />
                        Zobacz wszystkie ({homeworkAssignments.length}) prace domowe
                      </Button>
                    </Link>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </div>



        {/* Calendar Section */}
        <div className="mt-12">
          <CalendarView 
            userRole="student" 
            userId={isDemoMode && selectedStudentId ? selectedStudentId : (user as any)?.id || ""}
            showAllEvents={false}
          />
        </div>
          </div> {/* Close content container div */}
        </div> {/* Close main dashboard content div */}
      </div> {/* Close main content area div */}

      {/* Lesson Details Dialog */}
      <Dialog open={isLessonDialogOpen} onOpenChange={setIsLessonDialogOpen}>
        <DialogContent className="max-w-full sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-lg sm:text-xl font-bold text-navy-900">
              Szczegóły lekcji
            </DialogTitle>
          </DialogHeader>
          {selectedLesson && (
            <div className="space-y-4">
              <div>
                <h3 className="font-semibold text-lg text-navy-900 mb-2">
                  {selectedLesson.title}
                </h3>
                <div className="space-y-2 text-sm text-gray-600">
                  <div className="flex items-center gap-2">
                    <Clock className="w-4 h-4" />
                    <span>{new Date(selectedLesson.scheduledAt).toLocaleDateString("pl-PL")} o {new Date(selectedLesson.scheduledAt).toLocaleTimeString("pl-PL", { hour: '2-digit', minute: '2-digit' })}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Star className="w-4 h-4" />
                    <span>Korepetytor: {selectedLesson.tutorName || selectedLesson.tutor}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <BookOpen className="w-4 h-4" />
                    <span>Czas trwania: {selectedLesson.duration || 60} minut</span>
                  </div>
                </div>
              </div>
              
              {selectedLesson.description && (
                <div>
                  <h4 className="font-medium text-navy-900 mb-1">Opis lekcji:</h4>
                  <p className="text-sm text-gray-600">{selectedLesson.description}</p>
                </div>
              )}

              {/* Google Meet Link Section */}
              {selectedLesson.meetLink && (
                <div className="bg-blue-50 p-3 rounded-lg">
                  <h4 className="font-medium text-navy-900 mb-2 flex items-center gap-2">
                    <Video className="w-4 h-4" />
                    Link Google Meet
                  </h4>
                  <div className="flex items-center gap-2">
                    <div className="bg-white px-3 py-2 rounded border text-xs font-mono flex-1 truncate">
                      {selectedLesson.meetLink}
                    </div>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => handleCopyMeetLink(selectedLesson)}
                    >
                      <Copy className="w-3 h-3" />
                    </Button>
                  </div>
                </div>
              )}

              <div className="pt-4 border-t border-gray-200 space-y-2">
                {(() => {
                  const lessonDate = new Date(selectedLesson.scheduledAt);
                  const today = new Date();
                  const isPastLesson = lessonDate < today;
                  
                  return (
                    <Button 
                      className={`w-full ${
                        isPastLesson 
                          ? 'bg-gray-400 text-gray-600 hover:bg-gray-500 cursor-not-allowed' 
                          : 'bg-navy-900 text-white hover:bg-navy-800'
                      }`}
                      onClick={() => {
                        if (!isPastLesson) {
                          handleJoinLesson(selectedLesson);
                          setIsLessonDialogOpen(false);
                        }
                      }}
                      disabled={isPastLesson}
                    >
                      <Video className="w-4 h-4 mr-2" />
                      {isPastLesson ? 'Lekcja już się odbyła' : 'Dołącz do lekcji Google Meet'}
                    </Button>
                  );
                })()}
                
                {selectedLesson.meetLink && (
                  <Button 
                    variant="outline"
                    className="w-full border-navy-200 text-navy-600 hover:bg-navy-50"
                    onClick={() => handleCopyMeetLink(selectedLesson)}
                  >
                    <Copy className="w-4 h-4 mr-2" />
                    Kopiuj link spotkania
                  </Button>
                )}
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Payment Modal */}
      {paymentLessonId && (
        <LessonPayment
          lessonId={paymentLessonId}
          lessonTitle={selectedLesson?.title || "Lekcja matematyki"}
          lessonAmount="100.00"
          isOpen={isPaymentModalOpen}
          onClose={() => {
            setIsPaymentModalOpen(false);
            setPaymentLessonId("");
          }}
        />
      )}
    </div>
    </>
  );
}
